// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kumpklmvztdyorpdwymr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1bXBrbG12enRkeW9ycGR3eW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY0NzA1MzQsImV4cCI6MjA1MjA0NjUzNH0.Mh0zr9dqRkmFe9S_6DpMe7_Er1Woffr3CGOjS2Vw-Rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);